/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package segundacalculator.Apresetacao;

import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import segundacalculator.Modelo.Arquivo;
import segundacalculator.Modelo.Controle;
import segundacalculator.Modelo.Pedido;
import segundacalculator.Modelo.status;

/**
 *
 * @author Dell-9BQM7S1
 */
public class FrmAlmoxerifado extends javax.swing.JFrame
{

    /**
     * Creates new form FrmAlmoxerifado
     */
    private int Pedidoatual;
    private int QtPedido;
    private List<List> Pedidos;
    private Controle cont;
    private String txapedidos = "";
    
    public FrmAlmoxerifado() throws IOException
    {
        
        initComponents();
        
       Controle controle=new Controle();
       controle.lerarquivo();
       status status1=new status(controle.getPedido());
       this.Pedidos=status1.validarString();
        System.out.println(this.Pedidos.size());
       this.QtPedido=this.Pedidos.size();
       this.Pedidoatual=0;
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnProxPedido = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblNomee = new javax.swing.JLabel();
        lblProduto = new javax.swing.JLabel();
        lblRua = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        btnFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnProxPedido.setText("Proximo Pedido");
        btnProxPedido.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnProxPedidoActionPerformed(evt);
            }
        });

        lblNome.setText("Nome:");

        jLabel1.setText("Produto:");

        jLabel2.setText("Rua:");

        jLabel3.setText("nº");

        jLabel4.setText("Cidade:");

        jLabel5.setText("Valor Total");

        btnFinalizar.setText("Finalizar Pedido");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(175, 175, 175)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblRua, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(lblCidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNomee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(btnProxPedido)
                .addGap(97, 97, 97)
                .addComponent(btnFinalizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNome)
                    .addComponent(lblNomee, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRua, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProxPedido)
                    .addComponent(btnFinalizar))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProxPedidoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnProxPedidoActionPerformed
    {//GEN-HEADEREND:event_btnProxPedidoActionPerformed
       if (this.Pedidoatual<this.QtPedido)
       {
     
           if(this.Pedidos.get(this.Pedidoatual).get(6).equals("0"))
           {
                lblNome.setText((String) this.Pedidos.get(this.Pedidoatual).get(0));
                lblProduto.setText((String) this.Pedidos.get(this.Pedidoatual).get(1));
                lblRua.setText((String) this.Pedidos.get(this.Pedidoatual).get(2));
                lblNumero.setText((String) this.Pedidos.get(this.Pedidoatual).get(3));
                lblCidade.setText((String) this.Pedidos.get(this.Pedidoatual).get(4));
                lblValorTotal.setText((String) this.Pedidos.get(this.Pedidoatual).get(5));
                this.Pedidos.get(this.Pedidoatual).set(6,1);
            }
           else
           {
               
               int pedidoValido = this.Pedidoatual;
               
               while (this.Pedidos.get(pedidoValido).get(6).equals("1"))
               {                   
                   pedidoValido += 1;
               }
               
               lblNome.setText((String) this.Pedidos.get(pedidoValido).get(0));
               lblProduto.setText((String) this.Pedidos.get(pedidoValido).get(1));
               lblRua.setText((String) this.Pedidos.get(pedidoValido).get(2));
               lblNumero.setText((String) this.Pedidos.get(pedidoValido).get(3));
               lblCidade.setText((String) this.Pedidos.get(pedidoValido).get(4));
               lblValorTotal.setText((String) this.Pedidos.get(pedidoValido).get(5));
               this.Pedidos.get(pedidoValido).set(6,1);
               
               this.Pedidoatual = pedidoValido - 1;
               
           }
          
      
        this.Pedidoatual+=1;
        
       }
       
       
        
    }//GEN-LAST:event_btnProxPedidoActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnFinalizarActionPerformed
    {//GEN-HEADEREND:event_btnFinalizarActionPerformed
        Arquivo arquivo=new Arquivo("teste.txt");
       
        try
        {
            arquivo.sobrescrever();
        }
        catch (IOException ex)
        {
            Logger.getLogger(FrmAlmoxerifado.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            String linhas = "";
            String linha;
            
            for (int i = 0; i < this.Pedidos.size(); i++)
            {
                
                linha = "";
                
                for (int j = 0; j < Pedidos.get(i).size(); j++)
                {
                    linha += this.Pedidos.get(i).get(j) + ",";
                    
                    
                }
                
                
                linha += "\r\n";
                linhas += linha;
                
            try
            {
                arquivo.escrever(linha);
            }
            catch (IOException ex)
            {
                Logger.getLogger(FrmAlmoxerifado.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            
            
            
            
       
    }//GEN-LAST:event_btnFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FrmAlmoxerifado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FrmAlmoxerifado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FrmAlmoxerifado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FrmAlmoxerifado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                try
                {
                    new FrmAlmoxerifado().setVisible(true);
                }
                catch (IOException ex)
                {
                    Logger.getLogger(FrmAlmoxerifado.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnProxPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomee;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblValorTotal;
    // End of variables declaration//GEN-END:variables
}
