/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package segundacalculator.Apresetacao;

import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import segundacalculator.Modelo.Controle;

/**
 *
 * @author Dell-9BQM7S1
 */
public class FrmAlmoxerifado extends javax.swing.JFrame
{

    /**
     * Creates new form FrmAlmoxerifado
     */
    
    private Controle cont;
    private String txapedidos = "";
    
    public FrmAlmoxerifado()
    {
        initComponents();
        
        Controle controle = new Controle();
        
        this.cont = controle;
        
        
        
        try
        {
            this.cont.lerarquivo();
            String pedidos = this.cont.getPedido();
            

            String[] pedido = pedidos.split(";");
            
            for( int i = 0; i < pedido.length; i++)
            {
                String[] campos = pedido[i].split(",");
                this.txapedidos = "Nome: " + campos[0] + "\r\n" +"Produto: " + campos[1];
                System.out.println(this.txapedidos);
                System.out.println(Arrays.toString(campos));
                txaPedidos.setText(this.txapedidos);
                
            }
            
            
            
            this.txaPedidos.setText(pedidos);
        }
        catch (IOException ex)
        {
            Logger.getLogger(FrmAlmoxerifado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnProxPedido = new javax.swing.JButton();
        lblPedido = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaPedidos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnProxPedido.setText("Proximo Pedido");
        btnProxPedido.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnProxPedidoActionPerformed(evt);
            }
        });

        txaPedidos.setColumns(20);
        txaPedidos.setRows(5);
        jScrollPane1.setViewportView(txaPedidos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 225, Short.MAX_VALUE)
                .addComponent(btnProxPedido)
                .addGap(147, 147, 147))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(btnProxPedido)
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProxPedidoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnProxPedidoActionPerformed
    {//GEN-HEADEREND:event_btnProxPedidoActionPerformed
        try
        {
            this.cont.lerarquivo();
        } catch (IOException ex)
        {
            Logger.getLogger(FrmAlmoxerifado.class.getName()).log(Level.SEVERE, null, ex);
        }
        String pedidos = this.cont.getPedido();
         this.txaPedidos.setText(pedidos);
    }//GEN-LAST:event_btnProxPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FrmAlmoxerifado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FrmAlmoxerifado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FrmAlmoxerifado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FrmAlmoxerifado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FrmAlmoxerifado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProxPedido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPedido;
    private javax.swing.JTextArea txaPedidos;
    // End of variables declaration//GEN-END:variables
}
